"""Validate module-level coverage thresholds and emit warnings.

Coverage enforcement strategy:
- Grace period: Until ENFORCEMENT_DATE (30 days from Story 1.11 completion)
- During grace period: Warnings only
- After grace period: CI failure on threshold violations
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Dict, Tuple


# Coverage enforcement date (30 days from 2025-11-16 = 2025-12-16)
# After this date, coverage below threshold will BLOCK CI (not just warn)
ENFORCEMENT_DATE = date(2025, 12, 16)


GroupThresholds = Dict[str, float]


def load_coverage(coverage_json: Path) -> Dict:
    if not coverage_json.exists():
        raise FileNotFoundError(f"Coverage JSON not found: {coverage_json}")
    return json.loads(coverage_json.read_text())


def compute_group_coverage(data: Dict, group_prefix: str) -> Tuple[float, int]:
    """Return (percent, files_count) for files under a given prefix."""
    files = data.get("files", {})
    statements = 0
    covered = 0

    for path, meta in files.items():
        if group_prefix not in path.replace("\\", "/"):
            continue
        summary = meta.get("summary", {})
        statements += int(summary.get("num_statements", 0))
        covered += int(summary.get("covered_lines", 0))

    if statements == 0:
        return 100.0, 0
    return round((covered / statements) * 100, 2), len(files)


def emit_warning(message: str) -> None:
    print(f"::warning::{message}")


def emit_error(message: str) -> None:
    print(f"::error::{message}")


def is_enforcement_active() -> bool:
    """Check if we're past the 30-day grace period."""
    today = date.today()
    return today >= ENFORCEMENT_DATE


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate coverage thresholds with 30-day grace period enforcement."
    )
    parser.add_argument(
        "--coverage-file",
        type=Path,
        default=Path("coverage.json"),
        help="Path to coverage JSON report generated by `coverage json`.",
    )
    parser.add_argument(
        "--warn-only",
        action="store_true",
        default=False,
        help="Override enforcement and only warn (for testing).",
    )
    args = parser.parse_args()

    data = load_coverage(args.coverage_file)
    thresholds: GroupThresholds = {
        "src/work_data_hub/domain/": 90.0,
        "src/work_data_hub/io/": 70.0,
        "src/work_data_hub/orchestration/": 60.0,
    }

    warnings = []
    for prefix, minimum in thresholds.items():
        percent, _ = compute_group_coverage(data, prefix)
        if percent < minimum:
            warnings.append(f"{prefix} coverage {percent:.2f}% < target {minimum}%")

    overall = data.get("totals", {})
    overall_pct = overall.get("percent_covered", overall.get("percent_covered_display"))
    if isinstance(overall_pct, str):
        try:
            overall_pct = float(overall_pct.strip("%"))
        except Exception:
            overall_pct = None
    if overall_pct is not None and overall_pct < 80.0:
        warnings.append(f"overall coverage {overall_pct:.2f}% < target 80%")

    # Determine if we should block or just warn
    enforce = is_enforcement_active() and not args.warn_only
    today = date.today()
    days_until_enforcement = (ENFORCEMENT_DATE - today).days

    if warnings:
        if enforce:
            # After grace period: BLOCK CI
            print(f"::error::Coverage enforcement is ACTIVE (past {ENFORCEMENT_DATE})")
            for warning in warnings:
                emit_error(warning)
            print("\nCoverage thresholds NOT met. CI BLOCKED.")
            for warning in warnings:
                print(f"- {warning}")
            sys.exit(1)
        else:
            # During grace period: WARN only
            if days_until_enforcement > 0:
                print(
                    f"::notice::Coverage warnings (grace period: {days_until_enforcement} days until enforcement on {ENFORCEMENT_DATE})"
                )
            else:
                print("::notice::Coverage warnings (enforcement overridden by --warn-only)")
            for warning in warnings:
                emit_warning(warning)
            print("Coverage thresholds NOT met. Warnings issued (grace period):")
            for warning in warnings:
                print(f"- {warning}")
    else:
        print("✅ Coverage thresholds met.")

    if enforce and warnings:
        sys.exit(1)


if __name__ == "__main__":
    main()
